apiVersion: v1
kind: Pod
metadata:
  name: labels-check
  labels:
    environment: production
    app: nginx

spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
      - containerPort: 80