apiVersion: v1
kind: Pod
metadata:
  name: labels-check
  annotations:
    com.project.environment: production
    com.project.author: Rashid-Khan

spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
      - containerPort: 80