apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
data:
  username: cmFzaGlkCg==
  password: YWJjMTIzCg==

---

apiVersion: v1
kind: Pod
metadata:
  name: envFromSecrets

spec:
  containers:
  - name: secrets-pod
    image: nginx
    envFrom:
    - secretRef:                # getting all key-value pairs at once from secret
      name: secret-basic-auth

  
