apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop     # has to match .spec.template.metadata.labels

  serviceName: "mysql-service"
  replicas: 1               # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql
        envFrom:
        - configMapRef:
            name: mysql-configmap
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None       # headless service
  selector:
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-service-port
    protocol: TCP
    port: 3306            # this port no belongs to service
    targetPort: 3306      # this port belongs to container

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
