
#=====================================================================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl-1
  labels: # these labels are deployment labels
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: app-1
  template:
    metadata:
      labels: # these labels are pod labels
        app: app-1
    spec:
      containers:
      - name: app-1
        image: app1:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        imagePullPolicy: Always

#=====================================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app-1
  ports:
  - protocol: TCP
    port: 80        #service-port
    targetPort: 80  #container-port

#=====================================================================================
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app1-ingress
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
        alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          service:
            name: app1-service
            port:
              number: 80