apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-1a/vol-xxxxxxxxxxxx
  capacity:
    storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:           # these lables are deployment labels                 
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:    # these labels should match with pod labels
      app: nginx
      project: roboshop
      component: frontend
  template:         # this is a pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-pv
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: ebs-static-pvc
