apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "ebs-sc"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:           # these lables are deployment labels                 
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:    # these labels should match with pod labels
      app: nginx
      project: roboshop
      component: frontend
  template:         # this is a pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-pv
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: ebs-dynamic-pvc
