kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-abc0123def456789a
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop" # optional

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:           # these lables are deployment labels                 
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:    # these labels should match with pod labels
      app: nginx
      project: roboshop
      component: frontend
  template:         # this is a pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-pv
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: efs-dynamic-pvc
