---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None       # headless service
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
  - name: mongodb-service-port
    protocol: TCP
    port: 27017           # this port no belongs to service
    targetPort: 27017     # this port belongs to container