apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
      app: nginx
      project: roboshop
      component: frontend
    
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: "{{ .values.service.port }}"                  # this port no belongs to service
    targetPort: http-web-svc  # this port belongs to container