apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-set
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop     # has to match .spec.template.metadata.labels

  serviceName: "redis-service"
  replicas: 1               # by default is 1
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis-pvc
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  clusterIP: None       # headless service
  selector:
    app: redis
    tier: db
    project: roboshop
  ports:
  - name: redis-service-port
    protocol: TCP
    port: 6379            # this port no belongs to service
    targetPort: 6379      # this port belongs to container