# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce
  region: us-east-1

managedNodeGroups:                # Completely Managed by AWS
  - name: ecommerce-spot-node
    instanceType: t2.micro
    desiredCapacity: 3
    spot: true                    # Your nodes can be takes back at any point of time
    ssh:
      publicKeyName: VirginiaKey  # Your Key pair in AWS